import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { TopNav } from "@/components/top-nav";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { BottomNav } from "@/components/bottom-nav";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>
              {/* layout wrapper */}
              <div className="flex flex-col min-h-svh w-full">
                {/* top-bar (now inside provider so SidebarTrigger works) */}
                <header className="sticky top-0 z-50 h-16 flex items-center px-4
                                  bg-background/70 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                  <TopNav />
                </header>

                {/* sidebar + page area */}
                <div className="flex flex-1">
                  <AppSidebar />           {/* left column */}
                  <main className="flex flex-col flex-1">
                    {children}
                    <BottomNav />
                  </main>
                </div>
              </div>
              <Toaster />
            </SidebarProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}